name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Semantic-Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Create .releaserc.json
        run: |
          echo '{
            "plugins": [
              "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator",
              [
                "@semantic-release/github",
                {
                  "assets": [{"path": "CHANGELOG.md"}]
                }
              ],
              [ 
                "@semantic-release/changelog",
                {
                  "changelogFile": "CHANGELOG.md"
                }
              ],
              "@semantic-release/git"
            ]
          }' > .releaserc.json
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main'
            ]
          tag_format: "v${version}"